### ISSUE TITLE
kaggle api returns 401 - Unauthorized

### ISSUE THREAD

**Issue by mhiro216** [Kaggle/kaggle-api#279]
I can't download kaggle data via kaggle api, either on local and on google colab.
I can download data on kaggle GUI, which means I successfully enrolled in the competition.

I followed the procedure on https://github.com/Kaggle/kaggle-api to use kaggle api.

Here are information on my environment.

```sh
ls /Users/.kaggle/
# ls /Users/.kaggle/
# kaggle.json
```

```sh
ls -l /Users/.kaggle/
# total 8
# -rw-r--r--@ 1 root  admin  64  6 26 18:59 kaggle.json
```

```sh
kaggle competitions list
# 401 - Unauthorized
```

```sh
kaggle competitions download -c global-wheat-detection
# 401 - Unauthorized
```

```sh
pip show kaggle
# Name: kaggle
# Version: 1.5.6
# Summary: Kaggle API
# Home-page: https://github.com/Kaggle/kaggle-api
# Author: Kaggle
# Author-email: support@kaggle.com
# License: Apache 2.0
# Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
# Requires: python-dateutil, requests, python-slugify, six, tqdm, certifi, urllib3
# Required-by:
```

I thought the api token was not made correctly, so I made them all expire and made a new token again, but it did not work.

I appreciate if anyone help me out.

**Comment by AlinaWithAFace** [comment]
I've also run into this issue!

**Comment by Chizuchizu** [comment]
I ran into the same problem, but after creating a new Kaggle Token, the problem was fixed!

**Comment by Quoding** [comment]
Ran into this problem as well, even when creating a new Kaggle Token and/or expiring all tokens before I'm still getting 401 Unauthorized.

**Comment by ChrisRichardMiles** [comment]
I overcame this issue by deleteing the kagge.json file and replacing it with a new one downloaded from kaggle. Its the file that goes exacty at root/.kaggle/kaggle.json

**Comment by mhiro216** [comment]
Thank you all. I resolved this issue with you all's process.

**Comment by AbdulQadir811** [comment]
I overcome this problem by creating a new API token and then replaced that with the older one.

**Comment by pepetikesavasiddhardha** [comment]
issue resolved for me when i took new api token and expired all previous ones and downloaded json file again from kaggle by deleting old json file. It works

**Comment by aeikay** [comment]
I had uploaded the JSON file into colab already while working, so even after creating a new token since I forgot to clear all the outputs from the kernel it was still showing an error. If anyone's working in google colab they should do a factory reset before uploading a new JSON file.

**Comment by Coding-Forest** [comment]
Hi. I ran into the same issue while following this guideline in google colab: 
https://www.kaggle.com/general/74235

I tried @Chizuchizu's tip, and it worked. 

1) Factory reset runtime
2) Expire and redownload a new API.

Thanks everyone!

**Comment by cmdecker95** [comment]
Same issue, but I also fixed it by creating a new API token!

For me, I think the issue was that I clicked "Expire" and "Create" _too close to each other_, so it may have created the new API token first _then expired it_. So **wait until the token expiration completes before creating a new token**.

**Comment by La-fe** [comment]
You can check if the following in ~ / .bashrc are the same as kaggle.json
```
export KAGGLE_USERNAME=datadinosaur
export KAGGLE_KEY=xxxxxxxxxxxxxx
```

**Comment by 01155847635** [comment]
I still have this problem , please help me

**Comment by JanSurft** [comment]
If your are on a jupyter instance: For me it helped to restart the kernel after updating the API Key.

**Comment by wvxvw** [comment]
So why is this closed? The code is definitely broken. If Kaggle cannot generate tokens, or have problems with their request validation or whatever else the problem is, they need to know about it / fix it.

Why close this issue if nothing was fixed?

**Comment by aaronjoseph** [comment]
Facing this issue here as well.

Tried to expire the tokens and run it (saved the json in ~/.kaggle/kaggle.json & also tried to do in bashrc with the export command + source command)

Still no luck. Suprising.

**Comment by bi1yeu** [comment]
What worked for me was creating a token without expiring the old one(s). Based on the toast notifications in the Kaggle web app, it looked like clicking "Expire API Token" followed by "Create New API Token" actually resulted in the new token getting created and then immediately being expired. When I clicked "Create" without first "Expire", the newly generated token worked as expected.

**Comment by NishaniKasineshan** [comment]
I ran into the same problem today.@bi1yeu tip worked for me.Thank you.

**Comment by Padmanabhan100** [comment]
> issue resolved for me when i took new api token and expired all previous ones and downloaded json file again from kaggle by deleting old json file. It works

Thanks  a lot man, it  worked!!

**Comment by aaronjoseph** [comment]
Okay, strangely enough, it started to work, my bad. 

FYI, try the EXPORT Command, it will precendence over the kaggle.json file. This was how it started to work in mine. Thanks

**Comment by Alphakitty54** [comment]
> how did u apply EXPORT, can you write th code for me

**Comment by Code2147483647** [comment]
Same problem here.
I repeat expire all token and then create new token but always 401 unauthorized...

**Comment by aaronjoseph** [comment]
So, do check your file manually as well. Which is placed at ~/kaggle/kaggle.json. Quite often the export commands don't update it.

**Comment by aaronjoseph** [comment]
> > how did u apply EXPORT, can you write th code for me

It's a Linux command to create a variable and assign it a value

**Comment by alghenab** [comment]
After renewing your API make sure you're code is the same as below.
`
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/kaggle.json
! chmod 600 ~/.kaggle/kaggle.json
! kaggle datasets list
`

**Comment by DilpatRai** [comment]
I am facing the same issue (ApiException: (401)) while downloading the dataset from Kaggle 
I gave the right credentials but still it is showing the same issue

**Comment by AngelikaAnnemarieKreutzer** [comment]
> Ich habe das gleiche Problem (ApiException: (401)) beim Herunterladen des Datensatzes von Kaggle . Ich habe die richtigen Anmeldeinformationen angegeben, aber es zeigt immer noch das gleiche Problem

Vorher war alles in Ordnung. Nur seit heute habe ich das gleiche Problem wie du.

**Comment by slives-lab** [comment]
All solutions described above don't work. The only solution is to manually download. Not sure why kaggle can't fix this issue:
401 - Unauthorized

**Comment by Fumeng-Yang** [comment]
I finally resolved this problem by running `sudo kaggle ...` (after KAGGLE_USERNAME is set). I think it is because I am not using the admin account and `chmod 600` only gives permission to the admin.

**Comment by The-EleetCoder** [comment]
> I overcame this issue by deleteing the kagge.json file and replacing it with a new one downloaded from kaggle. Its the file that goes exacty at root/.kaggle/kaggle.json

yes it worked!

**Comment by pault-tech** [comment]
In my case the issue was how kaggle cli was installed.

Saw this error after running:

pip install kaggle

but fixed after running:

pip uninstall kaggle
pip install --user kaggle 
(restart shell)

So the issue was actually which user/where the home directory was.

**Comment by JAYANTHNITW** [comment]
> I overcame this issue by deleteing the kagge.json file and replacing it with a new one downloaded from kaggle. Its the file that goes exacty at root/.kaggle/kaggle.json

I fixed my error with your suggestion thank you for helping the community

**Comment by cemsayilar** [comment]
hi everyone. i have my .kaggle directory with kaggle.json file in it. there is no syntax error with the key or anything else. i expired tokens and replace it. however problem persisted. 
**resolved 401 - Unauthorized issue with the following:**

mkdir ~/.kaggle
# cp command requires both a source file and a target location. In your command, you've only specified the source file (/Users/username/directory/.kaggle/kaggle.json). You also need to provide the destination where the file should be copied to.
cp /Users/yourusername/Downloads/kaggle.json ~/.kaggle/kaggle.json
kaggle datasets download -d <dataset_identifier>

**Comment by kietna1809** [comment]
I fix by reopen the terminal
