### ISSUE TITLE
Cannot download available dataset

### ISSUE THREAD

**Issue by zoomwe** [Kaggle/kaggle-api#68]
I am trying to run 

`kaggle datasets download -d madhab/jobposts`

However it returns 

`404 - Not Found`

I wonder why it so, because the dataset is available via the webpage https://www.kaggle.com/madhab/jobposts/

How can I download the dataset via API?

**Comment by rysteboe** [comment]
Found the bug, it's a server side issue with how we resolve the zip file name to the dataset.  Will have a fix out by Monday.

Sorry about that - thanks for the report!

**Comment by rysteboe** [comment]
Should be fixed in 1.4.4.  There was some wonkiness here though - please let me know if you continue to run into problems.

**Comment by manishprasadthapliyal** [comment]
Hi,
I am using kaggle version : Kaggle API 1.4.7.1
still getting not found issue for available dataset.

command : !kaggle competitions download -c tgs-salt-identification-challenge
result : 404 - Not Found

**Comment by rysteboe** [comment]
@manishprasadthapliyal have you accepted the competition's rules and are you able to download the dataset from the web UI?  Right now the error messages are not good around that (something to improve)

**Comment by NdaAzr** [comment]
Kaggle won't allow to download Carvana and tag salt, and gave me 500 -internal server error, however it could download the zillow/zecon

**Comment by AlanRMalta** [comment]
Hey - i have a similar issue. I am using 1.5.2 and get an error 404 for everything (i have signed up to the Commercial Aviation Fatalities competition, and am able to download the files from the GUI (just want to avoid having to then shift them to AWS) Thanks!

**Comment by jiangnanboy** [comment]
> 
> 
> I am trying to run
> 
> `kaggle datasets download -d madhab/jobposts`
> 
> However it returns
> 
> `404 - Not Found`
> 
> I wonder why it so, because the dataset is available via the webpage https://www.kaggle.com/madhab/jobposts/
> 
> How can I download the dataset via API?

downgrade kaggle version to 1.5.3
