### ISSUE TITLE
TypeError: 'NoneType' object is not iterable when uploading a dataset

### ISSUE THREAD

**Issue by chrisfilo** [Kaggle/kaggle-api#71]
Even though the [wiki](https://github.com/Kaggle/kaggle-api/wiki/Dataset-Metadata) states that the `resources` field in the dataset-metadata.json is not required I get the following error when uploading a dataset:
```
me@christop ~ $ kaggle datasets create -p /c/stanford_gdrive/data/ds000114/ --keep-tabular
Traceback (most recent call last):
  File "c:\users\me\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\me\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\Miniconda3\Scripts\kaggle.exe\__main__.py", line 9, in <module>
  File "c:\users\me\miniconda3\lib\site-packages\kaggle\cli.py", line 50, in main
    out = args.func(**command_args)
  File "c:\users\me\miniconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 714, in dataset_create_new_cli
    result = self.dataset_create_new(folder, public, quiet, convert_to_csv)
  File "c:\users\me\miniconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 679, in dataset_create_new
    self.validate_files_exist(folder, resources)
  File "c:\users\me\miniconda3\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 1399, in validate_files_exist
    for item in resources:
TypeError: 'NoneType' object is not iterable
```

My dataset-metadata.json file:
```
{
  "title": "BIDS test",
  "id": "chrisfilo/bids_test",
  "licenses": [
    {
      "name": "CC0-1.0"
    }
  ]
}
```

**Comment by rysteboe** [comment]
Fixed in the latest version (currently 1.4.4.).

**Comment by cyruszhang** [comment]
this problem still persists for me when I do: 
`kaggle datasets version`

the dataset metadata is pretty vanilla:
`{
  "title": "test_data_set",
  "id": "cyrusea/test_data_set",
  "licenses": [
    {
      "name": "CC0-1.0"
    }
  ]
}
`

**Comment by rysteboe** [comment]
@cyruszhang, what version of the API are you using?  `kaggle -v`

**Comment by cyruszhang** [comment]
1.4.6
I raised a separate issue, https://github.com/Kaggle/kaggle-api/issues/86, and seems you are already working on it

**Comment by cyruszhang** [comment]
just updated to 1.4.7.1; working for me now. thanks Rebecca!
