### ISSUE TITLE
Download files from subfolders doesn't work

### ISSUE THREAD

**Issue by setoff** [Kaggle/kaggle-api#739]
Tried the same code:

```python
from kaggle.api.kaggle_api_extended import KaggleApi

api = KaggleApi()
api.authenticate()

api.competition_download_file(
        <competition-name>, 
        'dataset/dataset_files/filename.ext' 
        path='local_path'
    )
```
Version 1.6.17 downloads file successfully.

Version 1.7.4.2 returns this error:
```
404 Client Error: Not Found for url: https://www.kaggle.com/api/v1/competitions/data/download/<competion-name>/dataset/dataset_files/filename.ext
```

**Comment by stevemessick** [comment]
@setoff I'm having trouble reproducing this. Can you give me an example using the command-line tool that works with 1.6.17? Thanks.

**Comment by setoff** [comment]
Sorry for the later reply.
You may use this one:
`kaggle competitions download --file kaggle-environments-0.1.4/kaggle_environments/static/player.html -c connectx`

With `Kaggle API 1.6.17` downloads file successfully.  
With `Kaggle API 1.7.4.2`:
```
404 Client Error: Not Found for url: https://www.kaggle.com/api/v1/competitions/data/download/connectx/kaggle-environments-0.1.4/kaggle_environments/static/player.html
```

**Comment by setoff** [comment]
@stevemessick added CLI to download file from one of the open competitions https://www.kaggle.com/competitions/connectx/overview

You need to join competition first and accept rules before running command I added in message above.

**Comment by stevemessick** [comment]
This should be fixed in the latest release, last week.

**Comment by MelonLord8** [comment]
The issue still persists now:
```
k_api.dataset_download_file(
                dataset="allen-institute-for-ai/CORD-19-research-challenge",
                file_name='Kaggle/target_tables/0_table_formats_and_column_definitions/column_definitions.docx',
                path="cache/",
                force=False
            )
```
(with all necessary imports)

returns this error:

```
Traceback (most recent call last):
  File "d:\StockDataPrep\main.py", line 29, in <module>
    k_api.dataset_download_file(
  File "D:\StockDataPrep\.venv\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 1617, in dataset_download_file
    response = kaggle.datasets.dataset_api_client.download_dataset(request)
  File "D:\StockDataPrep\.venv\lib\site-packages\kagglesdk\datasets\services\dataset_api_service.py", line 80, in download_dataset
    return self._client.call("datasets.DatasetApiService", "ApiDownloadDataset", request, HttpRedirect)
  File "D:\StockDataPrep\.venv\lib\site-packages\kagglesdk\kaggle_http_client.py", line 126, in call
    response = self._prepare_response(response_type, http_response)
  File "D:\StockDataPrep\.venv\lib\site-packages\kagglesdk\kaggle_http_client.py", line 191, in _prepare_response
    http_response.raise_for_status()
  File "D:\StockDataPrep\.venv\lib\site-packages\requests\models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.kaggle.com/api/v1/datasets/download/allen-institute-for-ai/CORD-19-research-challenge/Kaggle/target_tables/0_table_formats_and_column_definitions/column_definitions.docx?filename=Kaggle%2Ftarget_tables%2F0_table_formats_and_column_definitions%2Fcolumn_definitions.docx&raw=false
```
